version: '3.8'

services:
  api:
    build:
      args:
        - NODE_ENV=production
    command: npm run prod
    environment:
      - NODE_ENV=production

  nginx:
    build:
      args:
        - NODE_ENV=production
