version: '3.8'

services:
  db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app
      - MONGO_INITDB_ROOT_PASSWORD=app

  api:
    build:
      args:
        - NODE_ENV=production
    command: npm run prod
    environment:
      - NODE_ENV=production

  nginx:
    volumes:
      - ./nginx/dev.conf:/etc/nginx/sites-available/svg24.com.conf:ro
