version: '3.8'

services:
  db:
    container_name: platform-db
    build:
      context: .
      target: db
    restart: unless-stopped
    networks:
      nginx:
    volumes:
      - db:/srv/packages/db
    environment:
      - DATABASE_NAME=svg24
      - DATABASE_PASS=app
      - DATABASE_USER=app
      - MONGO_INITDB_ROOT_PASSWORD=app
      - MONGO_INITDB_ROOT_USERNAME=app

  root:
    container_name: platform-root
    build:
      context: .
      target: root
    networks:
      nginx:
    volumes:
      - root:/srv

  api:
    container_name: platform-api
    build:
      context: .
    depends_on:
      - db
      - root
    restart: unless-stopped
    networks:
      nginx:
    working_dir: /srv
    volumes:
      - root:/srv
      - db:/srv/packages/db
    environment:
      - DATABASE_DATA=/srv/packages/db/data
      - DATABASE_LOGOS=/srv/packages/db/logos
      - DATABASE_NAME=svg24
      - DATABASE_PASS=app
      - DATABASE_PORT=27017
      - DATABASE_USER=app
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000

  assets:
    container_name: platform-assets
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - root
    networks:
      nginx:
    working_dir: /srv
    volumes:
      - root:/srv
    environment:
      - SERVER_PORT=3000

  board:
    container_name: platform-board
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - root
    networks:
      nginx:
    working_dir: /srv
    volumes:
      - root:/srv

  www:
    container_name: platform-www
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - root
    networks:
      nginx:
    working_dir: /srv
    volumes:
      - root:/srv

  nginx:
    container_name: platform-nginx
    build:
      context: .
      args:
        - DOMAIN=svg24.dev
    depends_on:
      - api
      - board
    restart: unless-stopped
    networks:
      nginx:
    ports:
      - '443:443'
    command: nginx -g 'daemon off;'

networks:
  nginx:

volumes:
  db:
  root:
