version: '3.8'

services:
  db:
    container_name: platform-db
    build:
      context: .
      target: db
    restart: unless-stopped
    networks:
      nginx:
    volumes:
      - db:/srv/db
    environment:
      - DATABASE_NAME=svg24
      - DATABASE_PASS=app
      - DATABASE_USER=app
      - MONGO_INITDB_ROOT_PASSWORD=app
      - MONGO_INITDB_ROOT_USERNAME=app

  api:
    container_name: platform-api
    build:
      context: .
    depends_on:
      - db
    networks:
      nginx:
    volumes:
      - db:/srv/db
    environment:
      - DATABASE_DATA=/srv/db/data
      - DATABASE_LOGOS=/srv/db/logos
      - DATABASE_NAME=svg24
      - DATABASE_PASS=app
      - DATABASE_PORT=27017
      - DATABASE_USER=app
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000

  assets:
    container_name: platform-assets
    build:
      context: .
    restart: unless-stopped
    networks:
      nginx:
    environment:
      - SERVER_PORT=3000

  board:
    container_name: platform-board
    build:
      context: .
    networks:
      nginx:

  www:
    container_name: platform-www
    build:
      context: .
    networks:
      nginx:

  nginx:
    container_name: platform-nginx
    build:
      context: .
      args:
        - DOMAIN=svg24.dev
    depends_on:
      - api
      - board
    networks:
      nginx:
    ports:
      - '443:443'
    command: nginx -g 'daemon off;'

networks:
  nginx:

volumes:
  db:
