version: '3.8'

services:
  db:
    container_name: platform-db
    build:
      context: .
      target: db
      args:
        - DB_TARBALL=https://github.com/svg24/collection/tarball/main
    restart: unless-stopped
    networks:
      nginx:
    working_dir: /srv/db
    volumes:
      - db-srv:/srv/db
    environment:
      - DB_NAME=svg24
      - MONGO_INITDB_ROOT_USERNAME=app
      - MONGO_INITDB_ROOT_PASSWORD=app

  api:
    container_name: platform-api
    depends_on:
      - db
    restart: unless-stopped
    networks:
      nginx:
    working_dir: /srv/api
    volumes:
      - db-srv:/srv/db
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=3000
      - DB_NAME=svg24
      - DB_PASS=app
      - DB_PORT=27017
      - DB_USER=app

  assets:
    container_name: platform-assets
    restart: unless-stopped
    networks:
      nginx:
    working_dir: /srv/assets
    user: node
    command: npm run prod
    environment:
      - ASSETS_PORT=3000

  board:
    container_name: platform-board
    networks:
      nginx:
    working_dir: /srv/board

  nginx:
    container_name: platform-nginx
    build:
      context: .
      target: nginx
      args:
        - DOMAIN=svg24.dev
    depends_on:
      - api
      - board
    restart: unless-stopped
    networks:
      nginx:
    ports:
      - '80:80'
    command: nginx -g 'daemon off;'

networks:
  nginx:

volumes:
  db-srv:
