version: '3.8'

services:
  db:
    build:
      context: .
      target: db
      args:
        - DB_COLLECTION=logos
        - DB_TARBALL=https://github.com/svg24/platform/tarball/db
    container_name: svg24-db
    restart: unless-stopped
    networks:
      nginx:
    working_dir: /srv/db
    volumes:
      - db-srv:/srv/db
    environment:
      - DB_NAME=svg24
      - MONGO_INITDB_ROOT_USERNAME=app
      - MONGO_INITDB_ROOT_PASSWORD=app

  api:
    container_name: svg24-api
    restart: unless-stopped
    networks:
      nginx:
    depends_on:
      - db
    working_dir: /srv/api
    volumes:
      - db-srv:/srv/db
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=3000
      - DB_NAME=svg24
      - DB_PASS=app
      - DB_PORT=27017
      - DB_USER=app

  www:
    container_name: svg24-www
    networks:
      nginx:
    working_dir: /srv/www

  nginx:
    build:
      context: .
      target: nginx
      args:
        - DOMAIN=svg24.dev
    container_name: svg24-nginx
    restart: unless-stopped
    ports:
      - '80:80'
    networks:
      nginx:
    depends_on:
      - api
      - www
    command: nginx -g 'daemon off;'

networks:
  nginx:

volumes:
  db-srv:
