version: '3.8'

services:
  api:
    build:
      target: api-deps
    volumes:
      - ./packages/api:/srv/packages/api
      - /srv/packages/api/node_modules
    environment:
      - NODE_ENV=development
    user: node
    command: npm run dev:api

  assets:
    build:
      target: assets-deps
    volumes:
      - ./packages/assets:/srv/packages/assets
      - /srv/packages/assets/node_modules
    environment:
      - NODE_ENV=development
    user: node
    command: npm run dev:assets

  board:
    build:
      target: board-deps
    restart: unless-stopped
    volumes:
      - ./packages/board:/srv/packages/board
      - /srv/packages/board/node_modules
    environment:
      - NODE_ENV=development
      - BOARD_HMR_HOST=localhost
      - BOARD_HMR_PATH=ws
      - BOARD_HMR_PORT=80
      - BOARD_HMR_PROTOCOL=ws
      - BOARD_HOST=0.0.0.0
      - BOARD_PORT=3000
    user: node
    command: npm run dev:board

  nginx:
    build:
      target: nginx-dev
