version: '3.8'

services:
  api:
    build:
      target: api-deps
    volumes:
      - ./packages/api:/srv/packages/api
      - /srv/packages/api/node_modules
    environment:
      - NODE_ENV=development
    user: node
    command: yarn dev-api

  assets:
    build:
      target: assets-deps
    volumes:
      - ./packages/assets:/srv/packages/assets
      - /srv/packages/assets/node_modules
    environment:
      - NODE_ENV=development
    user: node
    command: yarn dev-assets

  board:
    build:
      target: board-deps
    volumes:
      - ./packages/board:/srv/packages/board
      - /srv/packages/board/node_modules
    environment:
      - BOARD_HMR_HOST=board.svg24.dev
      - BOARD_HMR_PATH=wss
      - BOARD_HMR_PORT=443
      - BOARD_HMR_PROTOCOL=wss
      - BOARD_HOST=0.0.0.0
      - BOARD_PORT=3000
      - NODE_ENV=development
    user: node
    command: yarn dev-board

  www:
    build:
      target: www-deps
    volumes:
      - ./packages/www:/srv/packages/www
      - /srv/packages/www/node_modules
    environment:
      - NODE_ENV=development
    user: node
    command: yarn dev-www

  nginx:
    build:
      target: nginx-dev
