version: '3.8'

services:
  root:
    container_name: platform-root
    build:
      context: .
      target: root-dev
    networks:
      nginx:
    volumes:
      - root:/srv
    environment:
      - NODE_ENV=development

  api:
    build:
      target: api-dev
    depends_on:
      - root
    volumes:
      - root:/srv
      - ./packages/api:/srv/packages/api
      - /srv/packages/api/node_modules
    environment:
      - NODE_ENV=development

  assets:
    build:
      target: assets-dev
    depends_on:
      - root
    volumes:
      - root:/srv
      - ./packages/assets:/srv/packages/assets
      - /srv/packages/assets/node_modules
    environment:
      - NODE_ENV=development

  board:
    build:
      target: board-dev
    restart: unless-stopped
    depends_on:
      - root
    volumes:
      - root:/srv
      - ./packages/board:/srv/packages/board
      - /srv/packages/board/node_modules
    environment:
      - NODE_ENV=development
      - SERVER_HMR_HOST=board.svg24.dev
      - SERVER_HMR_PATH=wss
      - SERVER_HMR_PORT=443
      - SERVER_HMR_PROTOCOL=wss
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000

  www:
    build:
      target: www-dev
    restart: unless-stopped
    depends_on:
      - root
    volumes:
      - root:/srv
      - ./packages/www:/srv/packages/www
      - /srv/packages/www/node_modules
    environment:
      - NODE_ENV=development
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000

  nginx:
    build:
      target: nginx-dev

volumes:
  root:
