version: '3.8'

services:
  api:
    build:
      context: .
      target: api-deps
    user: node
    command: npm run dev
    volumes:
      - ./packages/api:/srv/api
      - /srv/api/node_modules
    environment:
      - NODE_ENV=development

  board:
    build:
      context: .
      target: board-deps
    restart: unless-stopped
    user: node
    command: npm run dev
    volumes:
      - ./packages/board:/srv/board
      - /srv/board/node_modules
    environment:
      - NODE_ENV=development
      - BOARD_HMR_HOST=localhost
      - BOARD_HMR_PATH=ws
      - BOARD_HMR_PORT=80
      - BOARD_HMR_PROTOCOL=ws
      - BOARD_HOST=0.0.0.0
      - BOARD_PORT=3000

  nginx:
    build:
      args:
        - IS_DEV=true
