version: '3.8'

services:
  api:
    build:
      context: .
      target: api-prod
      args:
        - NODE_ENV=production
    user: node
    command: npm run prod
    environment:
      - NODE_ENV=production

  www:
    build:
      context: .
      target: www-prod
      args:
        - NODE_ENV=production
    user: app
    volumes:
      - www-srv:/srv/www
    environment:
      - NODE_ENV=production

  nginx:
    build:
      args:
        - IS_PREV
    volumes:
      - www-srv:/srv/www

volumes:
  www-srv:
