version: '3.8'

services:
  certbot:
    container_name: platform-certbot
    image: certbot/certbot
    depends_on:
      - nginx
    networks:
      nginx:
    volumes:
      - letsencrypt:/etc/letsencrypt

  nginx:
    build:
      target: nginx-prod
    volumes:
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
