version: '3.8'

services:
  nginx:
    build:
      target: nginx-prod
    volumes:
      - certbot:/var/www/html
      - letsencrypt:/etc/letsencrypt

volumes:
  certbot:
    driver: local
    driver_opts:
      type: none
      device: /srv/certbot
      o: bind
  letsencrypt:
    driver: local
    driver_opts:
      type: none
      device: /etc/letsencrypt
      o: bind
