version: '3.8'

services:
  nginx:
    build:
      args:
        - IS_PROD=true
    volumes:
      - dhparam:/etc/ssl/certs
      - platform_certbot-etc:/etc/letsencrypt
      - platform_certbot-lib:/var/lib/letsencrypt
    ports:
      - '443:443'

volumes:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /etc/ssl/certs
      o: bind
  platform_certbot-etc:
    external: true
  platform_certbot-lib:
    external: true
