version: '3.8'

services:
  nginx:
    build:
      target: nginx-prod
    volumes:
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
    driver: local
    driver_opts:
      type: none
      device: /etc/letsencrypt
      o: bind
