version: '3.8'

services:
  certbot:
    container_name: platform-certbot
    image: certbot/certbot
    networks:
      nginx:
    volumes:
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt

  nginx:
    build:
      target: nginx-prod
    volumes:
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt

volumes:
  certbot-www:
  letsencrypt:
