version: '3.8'

services:
  api:
    build:
      context: .
      target: api-prod
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    user: node
    command: npm run prod

  assets:
    build:
      args:
        - NODE_ENV=production

  board:
    build:
      context: .
      target: board-prod
      args:
        - NODE_ENV=production
    volumes:
      - board-srv:/srv/board
    environment:
      - NODE_ENV=production
    user: app

  nginx:
    build:
      args:
        - IS_PREV=true
    volumes:
      - board-srv:/srv/board

volumes:
  board-srv:
