### Get categories alphabetically
GET https://api.svg24.dev/v1/categories

{
  "data": {
    "A": {
      "id": "",
      "name": ""
    }
  },
  "meta": {}
}

### Get companies alphabetically
GET https://api.svg24.dev/v1/companies

{
  "data": {
    "A": {
      "id": "",
      "name": ""
    }
  },
  "meta": {}
}

### Find logos by filter
GET https://api.svg24.dev/v1/list
  ?category
  &company
  &multiplier
  &name
  &page
  &sortBy

{
  "data": [{
    "hasMore": "",
    "id": "",
    "latest": "",
    "name": "",
  }],
  "meta": {
    "length": {
      "current": "",
      "total": "",
    },
    "page": {
      "hasNext": "",
      "next": "",
    }
  }
}

### Find logo by id
GET https://api.svg24.dev/v1/item
  ?id

{
  "data": [{
    "content": {
      "components": {
        "js": {
          "react": "",
          "vue": ""
        },
        "ts": {
          "react": ""
        }
      },
      "links": {
        "url": ""
      },
      "snippets": {
        "css": "",
        "jsx": "",
        "svg": ""
      },
    },
    "version": {
      "date": "",
      "type": ""
    }
  }],
  "meta": {
    "category": "",
    "company": "",
    "date": "",
    "id": "",
    "name": "",
    "src": {
      "product": "",
      "usage": ""
    }
  }
}
