name: assets

on:
  push:
    branches: [main]
    paths:
      - "packages/assets/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: remove other package.json's
        run: |
          rm packages/api/package.json
          rm packages/board/package.json
          rm packages/collection/package.json
          rm packages/www/package.json
      - name: install deps
        run: yarn
      - name: lint
        run: |
          yarn lint-css-assets
          yarn lint-ts-assets

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: remove other package.json's
        run: |
          rm packages/api/package.json
          rm packages/board/package.json
          rm packages/collection/package.json
          rm packages/www/package.json
      - name: install deps
        run: yarn
      - name: build
        run: yarn build-assets
